trigger: none

resources:
  repositories:
    - repository: bis-schemas
      type: github
      endpoint: BisSchemasGitHub
      name: iTwin/bis-schemas

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_packages
    displayName: Build
    pool:
      vmImage: windows-latest

    workspace:
      clean: all
    steps:
      - checkout: self
        clean: all
      - checkout: bis-schemas
      - task: NodeTool@0
        displayName: 'Install Node 18.x'
        inputs:
          versionSpec: 18.x
          checkLatest: true

      - script: |
          cd /d $(System.DefaultWorkingDirectory)/bis-schema-validation
          dir
        displayName: 'dir bis-schema-validation'

      - publish: $(System.DefaultWorkingDirectory)/bis-schema-validation/schema-validator
        displayName: test publish
        artifact: schema-validator_Winx64