parameters: { npmToken: '' }

steps:
  - bash: |
      npm config set @bentley:registry=https://registry.npmjs.org/
      npm config set //registry.npmjs.org/:_authToken=${{ parameters.npmToken }}
      npm config set //registry.npmjs.org/:email='imodel.js@gmail.com'
      npm config set //registry.npmjs.org/:username='imodeljs'
    displayName: 'Seed npmrc'