parameters: { artifactsRegistryToken: '' }

steps:
  - bash: |
      npm config set @bentley:registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
      npm config set always-auth=true
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:username=bentleycs
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:_password=${{ parameters.artifactsRegistryToken }}
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:email="not used"
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:username=bentleycs
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:_password=${{ parameters.artifactsRegistryToken }}
      npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:email="not used"
    displayName: 'Seed npmrc'
    failOnStderr: false

