parameters:
  npmrcDir: ''
  artifactsRegistryToken: ''

steps:
  - powershell: |
      if(!(Test-Path -Path "${{ parameters.npmrcDir }}")) {
        mkdir "${{ parameters.npmrcDir }}"
      }

      $npmrcFile = "${{ parameters.npmrcDir }}" + "/.npmrc"

      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/"
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "always-auth=true" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:username=Packages" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:_password=${{ parameters.artifactsRegistryToken }}" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:email=npm requires email to be set but doesn't use the value" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:username=Packages" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:_password=${{ parameters.artifactsRegistryToken }}" -Append
      Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "//pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/:email=npm requires email to be set but doesn't use the value" -Append
    displayName: 'Seed npmrc'

