trigger:
- master

workspace:
  clean: all

pool:
  vmImage: windows-latest

steps:
  - checkout: self
  - script: 'git config --local user.email imodeljsbot@users.noreply.github.com'
    displayName: 'git config email'
  - script: 'git config --local user.name iModeljsBot'
    displayName: 'git config name'
  - script: 'git checkout --track origin/master'
    displayName: 'Switching to master '
  - task: NodeTool@0
    displayName: 'Install Node 18.x'
    inputs:
      versionSpec: 18.x
      checkLatest: true

  - script: node $(System.DefaultWorkingDirectory)/common/scripts/install-run-rush.js version --bump

    displayName: 'Update to new dev version on master'

  - script: |
      REM Adds the changes.
      git add .

      git status

    displayName: 'Git add'

  - powershell: |
      # Get the new version number.
      $json = Get-Content -Raw -Path common/config/rush/version-policies.json | ConvertFrom-Json

      $newVersion = $json[0].version

      Write-Host The new version is $newVersion
      Write-Host Committing version bump...

      git commit -m "$newVersion [skip ci]"

      Write-Host "##vso[build.updatebuildnumber]bis-schema-validation_$newVersion"

    displayName: 'Get version and committing'

  - script: 'git push --follow-tags https://$(GITHUBTOKEN)@github.com/iTwin/bis-schema-validation HEAD:master'
    displayName: 'Push version bump'
    condition: succeeded()
